const PRODUCTS = [
  {id:'lc-01',name:'Latch Aero 14',category:'Laptops',price:1299,was:1499,rating:4.8,stock:18,badges:['trending','deal'],blurb:'14-inch OLED, Ryzen AI, 32GB RAM'},
  {id:'lc-02',name:'Latch Forge 16',category:'Laptops',price:1899,rating:4.7,stock:11,badges:['new','best'],blurb:'RTX 4070 creator laptop, 1TB SSD'},
  {id:'lc-03',name:'Latch Fieldbook',category:'Laptops',price:999,rating:4.5,stock:24,badges:['best'],blurb:'All-day battery business ultrabook'},
  {id:'lc-04',name:'Latch Studio Pro 16',category:'Laptops',price:2499,was:2699,rating:4.9,stock:7,badges:['trending','new'],blurb:'Color-accurate display, 64GB RAM'},
  {id:'lc-05',name:'Latch Student 15',category:'Laptops',price:649,was:749,rating:4.4,stock:40,badges:['deal','best'],blurb:'Everyday laptop, 16GB / 512GB'},
  {id:'lc-06',name:'Latch Tower X',category:'Desktops',price:2199,rating:4.8,stock:9,badges:['trending','best'],blurb:'Ryzen 7 + RTX 4070 Super build'},
  {id:'lc-07',name:'Latch Office Mini',category:'Desktops',price:799,rating:4.6,stock:22,badges:['new'],blurb:'Quiet mini PC for desks and kiosks'},
  {id:'lc-08',name:'Latch Creator Station',category:'Desktops',price:3299,rating:4.9,stock:5,badges:['best'],blurb:'Threadripper-class workstation'},
  {id:'lc-09',name:'Latch Gamebox',category:'Desktops',price:1599,was:1799,rating:4.7,stock:14,badges:['deal','trending'],blurb:'1440p gaming tower, 32GB DDR5'},
  {id:'lc-10',name:'Latch Slate 11',category:'Tablets',price:499,rating:4.6,stock:30,badges:['new','trending'],blurb:'11-inch tablet with stylus support'},
  {id:'lc-11',name:'Latch Slate Pro 13',category:'Tablets',price:899,rating:4.8,stock:12,badges:['best'],blurb:'OLED tablet, keyboard cover included'},
  {id:'lc-12',name:'Latch Note Tab',category:'Tablets',price:349,was:399,rating:4.3,stock:28,badges:['deal'],blurb:'Media and classroom tablet'},
  {id:'lc-13',name:'Nova RTX 4060',category:'GPUs',price:329,rating:4.6,stock:20,badges:['best','deal'],blurb:'1080p/1440p graphics card'},
  {id:'lc-14',name:'Nova RTX 4070 Super',category:'GPUs',price:629,rating:4.8,stock:10,badges:['trending'],blurb:'High-refresh 1440p card'},
  {id:'lc-15',name:'Nova RTX 4080 Super',category:'GPUs',price:1049,rating:4.9,stock:6,badges:['best'],blurb:'4K gaming and CUDA workloads'},
  {id:'lc-16',name:'Nova Arc Creator',category:'GPUs',price:289,was:329,rating:4.4,stock:16,badges:['new','deal'],blurb:'Compact creator GPU'},
  {id:'lc-17',name:'Pulse Ryzen 5 7600',category:'CPUs',price:199,rating:4.7,stock:25,badges:['best'],blurb:'6-core AM5 gaming CPU'},
  {id:'lc-18',name:'Pulse Ryzen 7 7800X3D',category:'CPUs',price:389,rating:4.9,stock:8,badges:['trending','best'],blurb:'Cache-heavy gaming CPU'},
  {id:'lc-19',name:'Pulse Core Ultra 7',category:'CPUs',price:379,rating:4.6,stock:13,badges:['new'],blurb:'Efficient desktop processor'},
  {id:'lc-20',name:'Pulse Core i5-14600K',category:'CPUs',price:289,was:329,rating:4.5,stock:15,badges:['deal'],blurb:'Hybrid-core productivity CPU'},
  {id:'lc-21',name:'Latch DDR5 32GB Kit',category:'RAM',price:109,rating:4.7,stock:50,badges:['best','trending'],blurb:'6000 MT/s dual-channel kit'},
  {id:'lc-22',name:'Latch DDR5 64GB Kit',category:'RAM',price:199,rating:4.8,stock:18,badges:['new'],blurb:'Creator memory kit'},
  {id:'lc-23',name:'Latch DDR4 32GB Kit',category:'RAM',price:69,was:89,rating:4.5,stock:40,badges:['deal'],blurb:'3200 MHz upgrade kit'},
  {id:'lc-24',name:'Latch SODIMM 32GB',category:'RAM',price:89,rating:4.6,stock:22,badges:['new'],blurb:'Laptop memory upgrade'},
  {id:'lc-25',name:'Latch NVMe 1TB',category:'Storage',price:79,rating:4.8,stock:60,badges:['best'],blurb:'Gen4 SSD, 7000 MB/s class'},
  {id:'lc-26',name:'Latch NVMe 2TB',category:'Storage',price:139,rating:4.8,stock:34,badges:['trending'],blurb:'High-capacity Gen4 drive'},
  {id:'lc-27',name:'Latch NVMe 4TB',category:'Storage',price:279,was:319,rating:4.7,stock:12,badges:['deal','new'],blurb:'Creator archive SSD'},
  {id:'lc-28',name:'Latch Portable SSD 2TB',category:'Storage',price:159,rating:4.6,stock:19,badges:['best'],blurb:'USB-C pocket drive'},
  {id:'lc-29',name:'Latch HDD 8TB',category:'Storage',price:149,rating:4.4,stock:17,badges:['deal'],blurb:'Bulk backup hard drive'},
  {id:'lc-30',name:'Latch View 27 QHD',category:'Monitors',price:279,rating:4.7,stock:21,badges:['best','trending'],blurb:'165Hz IPS, 2560x1440'},
  {id:'lc-31',name:'Latch View 32 4K',category:'Monitors',price:499,rating:4.8,stock:9,badges:['new'],blurb:'4K productivity display'},
  {id:'lc-32',name:'Latch Curve 34',category:'Monitors',price:549,was:629,rating:4.6,stock:8,badges:['deal'],blurb:'Ultrawide 144Hz'},
  {id:'lc-33',name:'Latch Portable 16',category:'Monitors',price:199,rating:4.5,stock:14,badges:['new'],blurb:'USB-C travel monitor'},
  {id:'lc-34',name:'Latch Click Pro',category:'Mice',price:79,rating:4.8,stock:45,badges:['best','trending'],blurb:'Lightweight wireless mouse'},
  {id:'lc-35',name:'Latch Click Office',category:'Mice',price:29,rating:4.4,stock:70,badges:['deal'],blurb:'Silent multi-device mouse'},
  {id:'lc-36',name:'Latch Click Vertical',category:'Mice',price:49,rating:4.5,stock:26,badges:['new'],blurb:'Ergonomic vertical mouse'},
  {id:'lc-37',name:'Latch Track Glass',category:'Mice',price:129,rating:4.7,stock:11,badges:['trending'],blurb:'Glass pad compatible sensor'},
  {id:'lc-38',name:'Latch Key 75',category:'Keyboards',price:139,rating:4.8,stock:23,badges:['best','new'],blurb:'Hot-swap 75% mechanical'},
  {id:'lc-39',name:'Latch Key Low',category:'Keyboards',price:99,rating:4.6,stock:31,badges:['trending'],blurb:'Low-profile wireless keyboard'},
  {id:'lc-40',name:'Latch Key Full',category:'Keyboards',price:79,was:99,rating:4.4,stock:27,badges:['deal'],blurb:'Full-size quiet office board'},
  {id:'lc-41',name:'Latch Key 60',category:'Keyboards',price:119,rating:4.7,stock:16,badges:['new'],blurb:'Compact gasket-mount board'},
  {id:'lc-42',name:'Latch Dock 12-in-1',category:'Accessories',price:89,rating:4.6,stock:33,badges:['best'],blurb:'HDMI, SD, Ethernet, USB-C dock'},
  {id:'lc-43',name:'Latch USB-C 140W',category:'Accessories',price:59,rating:4.7,stock:40,badges:['trending'],blurb:'GaN laptop charger'},
  {id:'lc-44',name:'Latch Webcam 4K',category:'Accessories',price:119,rating:4.5,stock:18,badges:['new'],blurb:'4K conference camera'},
  {id:'lc-45',name:'Latch Headset ANC',category:'Accessories',price:149,was:179,rating:4.6,stock:20,badges:['deal','best'],blurb:'Wireless noise-cancelling headset'},
  {id:'lc-46',name:'Latch Mesh Wi-Fi 7',category:'Networking',price:299,rating:4.7,stock:13,badges:['new','trending'],blurb:'Tri-band mesh 2-pack'},
  {id:'lc-47',name:'Latch Switch 8',category:'Networking',price:49,rating:4.5,stock:29,badges:['best'],blurb:'2.5Gb unmanaged switch'},
  {id:'lc-48',name:'Latch NAS 4-Bay',category:'Networking',price:459,rating:4.6,stock:7,badges:['new'],blurb:'Home and office storage box'},
  {id:'lc-49',name:'Latch Sleeve 14',category:'Accessories',price:29,rating:4.3,stock:50,badges:['deal'],blurb:'Padded laptop sleeve'},
  {id:'lc-50',name:'Latch Stand Aluminum',category:'Accessories',price:39,rating:4.6,stock:36,badges:['best'],blurb:'Adjustable laptop stand'},
  {id:'lc-51',name:'Latch Capture Card',category:'Accessories',price:129,rating:4.5,stock:15,badges:['trending'],blurb:'4K60 HDMI capture'},
  {id:'lc-52',name:'Latch Cooling Pad',category:'Accessories',price:35,was:45,rating:4.2,stock:42,badges:['deal'],blurb:'Dual-fan laptop cooler'},
  {id:'lc-53',name:'Latch Motherboard B650',category:'Hardware',price:179,rating:4.6,stock:14,badges:['best'],blurb:'AM5 board, Wi-Fi 6E'},
  {id:'lc-54',name:'Latch PSU 850W Gold',category:'Hardware',price:129,rating:4.8,stock:19,badges:['trending'],blurb:'Fully modular ATX 3.1 PSU'},
  {id:'lc-55',name:'Latch Case Airflow',category:'Hardware',price:99,rating:4.5,stock:21,badges:['new'],blurb:'Mesh mid-tower, 4 fans'},
  {id:'lc-56',name:'Latch AIO 360',category:'Hardware',price:149,was:179,rating:4.7,stock:10,badges:['deal','best'],blurb:'360mm liquid cooler'},
  {id:'lc-57',name:'Latch Tablet Keyboard',category:'Accessories',price:79,rating:4.4,stock:17,badges:['new'],blurb:'Backlit folio for Slate Pro'},
  {id:'lc-58',name:'Latch Pen 2',category:'Accessories',price:59,rating:4.6,stock:24,badges:['trending'],blurb:'Pressure-sensitive stylus'},
  {id:'lc-59',name:'Latch Hub Mini',category:'Accessories',price:25,rating:4.3,stock:55,badges:['deal'],blurb:'4-port USB-C hub'},
  {id:'lc-60',name:'Latch Office Bundle',category:'Desktops',price:1099,was:1249,rating:4.7,stock:8,badges:['deal','best'],blurb:'Mini PC, 27-inch monitor, keyboard, mouse'},
  {id:'lc-61',name:'Latch Aero 13',category:'Laptops',price:1099,rating:4.6,stock:16,badges:['new'],blurb:'13-inch OLED travel laptop, 16GB'},
  {id:'lc-62',name:'Latch Forge 14 RTX',category:'Laptops',price:1699,was:1849,rating:4.7,stock:9,badges:['trending','deal'],blurb:'Thin RTX 4060 gaming laptop'},
  {id:'lc-63',name:'Latch Campus 14',category:'Laptops',price:549,was:629,rating:4.3,stock:38,badges:['deal'],blurb:'Student laptop, 16GB / 512GB'},
  {id:'lc-64',name:'Latch Fieldbook Tough',category:'Laptops',price:1399,rating:4.5,stock:8,badges:['new'],blurb:'Spill-resistant business laptop'},
  {id:'lc-65',name:'Latch Studio 14',category:'Laptops',price:1799,rating:4.8,stock:6,badges:['best'],blurb:'Pantone-validated creator screen'},
  {id:'lc-66',name:'Latch Tower SFF',category:'Desktops',price:1299,rating:4.6,stock:11,badges:['new','trending'],blurb:'Small-form Ryzen 5 + RTX 4060'},
  {id:'lc-67',name:'Latch Gamebox Elite',category:'Desktops',price:2499,rating:4.8,stock:4,badges:['best'],blurb:'RTX 4080 Super, 64GB DDR5'},
  {id:'lc-68',name:'Latch Quiet Office',category:'Desktops',price:899,was:999,rating:4.5,stock:18,badges:['deal'],blurb:'Fan-quiet desktop for open offices'},
  {id:'lc-69',name:'Latch Slate Mini 8',category:'Tablets',price:279,was:329,rating:4.2,stock:26,badges:['deal'],blurb:'Pocket tablet with LTE option'},
  {id:'lc-70',name:'Latch Slate Draw 12',category:'Tablets',price:649,rating:4.7,stock:13,badges:['new','best'],blurb:'Pen-first tablet, 120Hz'},
  {id:'lc-71',name:'Nova RTX 4070',category:'GPUs',price:529,rating:4.7,stock:12,badges:['best'],blurb:'1440p sweet-spot graphics card'},
  {id:'lc-72',name:'Nova RTX 4060 Ti',category:'GPUs',price:399,was:449,rating:4.5,stock:15,badges:['deal'],blurb:'16GB creator variant'},
  {id:'lc-73',name:'Nova Arc Studio',category:'GPUs',price:219,rating:4.3,stock:20,badges:['new'],blurb:'Entry creator card, low power'},
  {id:'lc-74',name:'Pulse Ryzen 9 7900',category:'CPUs',price:369,rating:4.7,stock:10,badges:['trending'],blurb:'12-core creator CPU'},
  {id:'lc-75',name:'Pulse Core Ultra 5',category:'CPUs',price:249,was:279,rating:4.4,stock:17,badges:['deal','new'],blurb:'Efficient 14-core desktop chip'},
  {id:'lc-76',name:'Pulse Ryzen 5 9600',category:'CPUs',price:229,rating:4.6,stock:14,badges:['new'],blurb:'Zen 5 six-core'},
  {id:'lc-77',name:'Latch Board Z890',category:'Hardware',price:289,rating:4.6,stock:9,badges:['new','trending'],blurb:'LGA1851, Wi-Fi 7, DDR5'},
  {id:'lc-78',name:'Latch Board B850',category:'Hardware',price:199,rating:4.5,stock:16,badges:['best'],blurb:'AM5 midrange, 2.5G LAN'},
  {id:'lc-79',name:'Latch DDR5 96GB Kit',category:'RAM',price:329,rating:4.7,stock:6,badges:['new'],blurb:'2x48GB creator kit'},
  {id:'lc-80',name:'Latch SODIMM 16GB',category:'RAM',price:45,was:59,rating:4.4,stock:48,badges:['deal'],blurb:'Laptop single-stick upgrade'},
  {id:'lc-81',name:'Latch NVMe Gen5 2TB',category:'Storage',price:229,rating:4.8,stock:9,badges:['trending','new'],blurb:'PCIe 5.0 boot drive'},
  {id:'lc-82',name:'Latch microSD 1TB',category:'Storage',price:89,rating:4.3,stock:30,badges:['deal'],blurb:'V30 card for cameras and tablets'},
  {id:'lc-83',name:'Latch View 24 Office',category:'Monitors',price:149,was:179,rating:4.4,stock:32,badges:['deal','best'],blurb:'1080p IPS, USB-C power'},
  {id:'lc-84',name:'Latch View 27 OLED',category:'Monitors',price:799,rating:4.9,stock:5,badges:['trending','best'],blurb:'240Hz QD-OLED gaming'},
  {id:'lc-85',name:'Latch Dual Arm',category:'Accessories',price:69,rating:4.6,stock:22,badges:['best'],blurb:'Gas-spring dual monitor arm'},
  {id:'lc-86',name:'Latch Click Ambi',category:'Mice',price:59,rating:4.5,stock:28,badges:['new'],blurb:'Ambidextrous wireless mouse'},
  {id:'lc-87',name:'Latch Click Macro',category:'Mice',price:69,was:79,rating:4.4,stock:19,badges:['deal'],blurb:'12-button MMO mouse'},
  {id:'lc-88',name:'Latch Key TKL',category:'Keyboards',price:109,rating:4.6,stock:18,badges:['trending'],blurb:'Tenkeyless hot-swap, linear'},
  {id:'lc-89',name:'Latch Key NumPad',category:'Keyboards',price:39,rating:4.3,stock:24,badges:['new'],blurb:'Wireless companion numpad'},
  {id:'lc-90',name:'Latch Headset Wired',category:'Accessories',price:49,was:69,rating:4.4,stock:34,badges:['deal'],blurb:'Boom mic, memory foam'},
  {id:'lc-91',name:'Latch Earbuds Desk',category:'Accessories',price:79,rating:4.5,stock:21,badges:['new'],blurb:'USB-C earbuds with dongle'},
  {id:'lc-92',name:'Latch Case Fans 3',category:'Hardware',price:39,rating:4.5,stock:40,badges:['deal','new'],blurb:'140mm PWM three-pack'},
  {id:'lc-93',name:'Latch PSU 650W',category:'Hardware',price:89,rating:4.6,stock:23,badges:['best'],blurb:'Gold modular power supply'},
  {id:'lc-94',name:'Latch Case ITX',category:'Hardware',price:79,rating:4.4,stock:12,badges:['new'],blurb:'Compact travel case, mesh'},
  {id:'lc-95',name:'Latch Wi-Fi 7 Card',category:'Networking',price:39,rating:4.5,stock:27,badges:['deal'],blurb:'Desktop PCIe wireless card'},
  {id:'lc-96',name:'Latch Router Wi-Fi 7',category:'Networking',price:199,rating:4.6,stock:11,badges:['trending','new'],blurb:'Single-unit Wi-Fi 7 router'},
  {id:'lc-97',name:'Latch Desk Mat XL',category:'Accessories',price:29,rating:4.6,stock:44,badges:['best'],blurb:'900x400 stitched desk mat'},
  {id:'lc-98',name:'Latch Cable Kit',category:'Accessories',price:19,was:29,rating:4.3,stock:60,badges:['deal'],blurb:'USB-C, HDMI, and display cables'},
  {id:'lc-99',name:'Latch KVM Switch',category:'Accessories',price:89,rating:4.5,stock:14,badges:['new'],blurb:'Dual-computer HDMI KVM'},
  {id:'lc-100',name:'Latch Stream Mic',category:'Accessories',price:99,rating:4.6,stock:13,badges:['trending'],blurb:'USB condenser with mute'},
  {id:'lc-101',name:'Latch Webcam Light',category:'Accessories',price:45,rating:4.4,stock:20,badges:['new'],blurb:'Bias light bar for calls'},
  {id:'lc-102',name:'Latch Tablet Stand',category:'Accessories',price:25,rating:4.3,stock:31,badges:['deal'],blurb:'Adjustable aluminum tablet stand'},
  {id:'lc-103',name:'Latch Gamebox Starter',category:'Desktops',price:999,was:1149,rating:4.5,stock:13,badges:['deal','trending'],blurb:'1080p tower, keyboard and mouse'},
  {id:'lc-104',name:'Latch View 49 Super',category:'Monitors',price:1099,rating:4.7,stock:3,badges:['trending','new'],blurb:'49-inch dual-QHD ultrawide'},
  {id:'lc-105',name:'Latch NAS Diskless 2',category:'Networking',price:219,rating:4.4,stock:9,badges:['best'],blurb:'Two-bay home NAS'},
  {id:'lc-106',name:'Latch Pen Tips',category:'Accessories',price:12,rating:4.2,stock:70,badges:['deal'],blurb:'Replacement nibs, 6 pack'},
  {id:'lc-107',name:'Latch Creator Bundle',category:'Desktops',price:2899,was:3199,rating:4.8,stock:4,badges:['best','deal'],blurb:'Creator station, 32-inch 4K, dock'},
  {id:'lc-108',name:'Latch Aero 16 OLED',category:'Laptops',price:1599,was:1749,rating:4.7,stock:10,badges:['new','trending'],blurb:'16-inch OLED, 32GB, 1TB Gen4'},
  {id:'lc-109',name:'Latch Rack Mini',category:'Desktops',price:649,rating:4.4,stock:15,badges:['new','deal'],blurb:'Quiet desk server, 32GB ECC option'},
  {id:'lc-110',name:'Latch Slate Ink 10',category:'Tablets',price:429,was:479,rating:4.5,stock:18,badges:['new'],blurb:'10-inch paper-feel tablet, stylus'},
  {id:'lc-111',name:'Nova RTX 4090',category:'GPUs',price:1699,rating:4.9,stock:3,badges:['new','best'],blurb:'Flagship 24GB CUDA card'},
  {id:'lc-112',name:'Pulse Ryzen 7 9700X',category:'CPUs',price:329,rating:4.7,stock:11,badges:['new','trending'],blurb:'Zen 5 eight-core, AM5'},
  {id:'lc-113',name:'Latch DDR5 16GB Kit',category:'RAM',price:59,was:69,rating:4.3,stock:42,badges:['new','deal'],blurb:'6000 MT/s starter kit'},
  {id:'lc-114',name:'Latch NVMe 512GB',category:'Storage',price:49,rating:4.4,stock:36,badges:['new'],blurb:'Gen4 boot SSD, 5000 MB/s class'},
  {id:'lc-115',name:'Latch View 27 IPS',category:'Monitors',price:229,rating:4.6,stock:17,badges:['new','best'],blurb:'144Hz IPS, USB-C 65W'}
];
